SetiQyu/Lab1-DECIDE

app/src/main/java/DECIDE/Decide.java
Implements a code skeleton with the global variables and datatypes described in Issue #4.
=> Code skeleton

.gitignore
fixes #1 
Now the .gitignore is properly updated with this.
=> Properly fixed issue #1

app/src/main/java/app/decide/Decide.java, app/src/test/java/app/decide/DecideTest.java
Rename package DECIDE to app.decide to be in accordance with java best practices
Fixes #2
=> refactor: Issue #2 rename decide package

app/src/main/java/app/decide/lic/ILic.java
Implement the LIC interface
Fixes #16
=> feature: #16 add skeleton for LICs, ILic interface

app/src/main/java/app/decide/PUMGenerator.java, app/src/test/java/app/decide/PUMGeneratorTest.java
Add PUMGenerator and it's tests
fixes #22
=> Fix issue #22

app/src/main/java/app/decide/Fuv.java, app/src/test/java/app/decide/FuvTest.java
Tests and functionality implemented as according to the specification. No documentation yet but will add when we have a common documentation solution worked out. 
Fixes #5
=> FUV and tests implemented (#5)

app/src/main/java/app/decide/PUMGenerator.java
Use switch expression in `PUMGenerator` as discussed in #25
Closes #38
=> refactor: #38 use switch expression in PUMGenerator

app/src/main/java/app/decide/lic/Lic5.java, app/src/test/java/app/decide/lic/Lic5Test.java
=> feature: #19 implement LIC 5

app/src/main/java/app/decide/lic/Lic6.java, app/src/test/java/app/decide/lic/Lic6Test.java
=> feature: #20 implement LIC 6

app/src/main/java/app/decide/lic/Lic7.java, app/src/test/java/app/decide/lic/Lic7Test.java
=> feature: #21 implement LIC 7

app/src/main/java/app/decide/Fuv.java, app/src/test/java/app/decide/FuvTest.java
This adds some much needed documentation to Fuv.java
fixes #40
=> fix: #40 Add documentation to Fuv

app/src/main/java/app/decide/lic/Lic10.java, app/src/test/java/app/decide/Lic10Test.java, app/src/test/java/app/decide/lic/Lic10Test.java
Implemented first version of LIC10 and 3 tests to test the functionality.
Closes #26
=> Feature: #26 LIC 10 and corresponding tests

app/src/main/java/app/decide/lic/Lic11.java, app/src/test/java/app/decide/Lic11Test.java, app/src/test/java/app/decide/lic/Lic11Test.java
Implements the functionality associated with Lic11. This version also includes 3 tests that ensures the functionality of the code.
Closes #27
=> Feature: #27 Lic11 implementation

app/src/main/java/app/decide/lic/Lic12.java, app/src/test/java/app/decide/Lic12Test.java, app/src/test/java/app/decide/lic/Lic12Test.java
Adds the required functionality for Lic12 and 3 corresponding tests.
Closes #28
=> Feature: #28 Implement Lic12

app/src/main/java/app/decide/lic/Lic8.java, app/src/test/java/app/decide/lic/Lic8Test.java
=> feature: #23 implement LIC 8

app/src/main/java/app/decide/lic/Lic14.java, app/src/test/java/app/decide/Lic14Test.java, app/src/test/java/app/decide/lic/Lic14Test.java
Implementation of Lic14 and corresponding tests.
Closes #30
=> Feature: #30 Implement Lic14

app/src/main/java/app/decide/lic/Lic13.java, app/src/test/java/app/decide/Lic13Test.java, app/src/test/java/app/decide/lic/Lic13Test.java
Implements the functionality of Lic13 and corresponding tests.
Closes #29
=> Feature: #29 Implement Lic13

app/src/main/java/app/decide/lic/Lic5.java, app/src/main/java/app/decide/lic/Lic6.java, app/src/main/java/app/decide/lic/Lic7.java, app/src/main/java/app/decide/lic/Lic8.java, app/src/main/java/app/decide/lic/Lic9.java, app/src/test/java/app/decide/lic/Lic5Test.java, app/src/test/java/app/decide/lic/Lic6Test.java, app/src/test/java/app/decide/lic/Lic7Test.java, app/src/test/java/app/decide/lic/Lic8Test.java, app/src/test/java/app/decide/lic/Lic9Test.java
Corrected the preconditions for LICs 9-5, corrected tests and added javadoc
=> fix: correct preconditions and javadoc for LICs 5 to 9

app/src/main/java/app/decide/lic/Lic0.java, app/src/test/java/app/decide/lic/Lic0Test.java
=> feature: #58 Implement LIC 0

app/src/main/java/app/decide/lic/Lic1.java, app/src/test/java/app/decide/lic/Lic1Test.java
=> feature: #55 implement LIC 1

app/src/main/java/app/decide/lic/Lic2.java, app/src/test/java/app/decide/lic/Lic2Test.java
=> feature: #56 implement LIC 2

app/src/main/java/app/decide/lic/Lic3.java, app/src/test/java/app/decide/lic/Lic3Test.java
=> feature: #57 implement LIC 3

app/src/main/java/app/decide/lic/Lic4.java, app/src/test/java/app/decide/lic/Lic4Test.java
=> feature: #61 implement LIC 4

app/src/main/java/app/decide/lic/Lic1.java, app/src/test/java/app/decide/lic/Lic1Test.java
=> fix: #66 fix Lic1 not checking input length

app/src/main/java/app/decide/Decide.java, app/src/test/java/app/decide/DecideTest.java
fixes #49 
Modified PR #50 without the user input. Builds ok and tests pass.
=> feature: #49 Implement decide logic

app/src/main/java/app/decide/Fuv.java, app/src/test/java/app/decide/FuvTest.java
This also should address #69 for FUV since the test cases formatting was updated. 
fixes #42
=> Fix: #42 Add error-handling and tests for FUV

app/src/test/java/app/decide/lic/Lic5Test.java, app/src/test/java/app/decide/lic/Lic6Test.java, app/src/test/java/app/decide/lic/Lic7Test.java, app/src/test/java/app/decide/lic/Lic8Test.java, app/src/test/java/app/decide/lic/Lic9Test.java
Add the LIC condition for lics 5-9 according to the feedback
Closes #75
=> doc: #75 add LIC condition specification as test class javadoc for LICs 5-9

README.md
If there is anything missing or any suggestions of change then feel free to let me know!
=> Fix: #68 updated README according to feedback

app/src/test/java/app/decide/DecideTest.java, app/src/test/java/app/decide/PUMGeneratorTest.java
fixes #79 #69 
This should hopefully make all files be compliant
=> Fix: #79 #69 All tests format fixed

app/src/main/java/app/decide/lic/Lic4.java, app/src/test/java/app/decide/lic/Lic1Test.java, app/src/test/java/app/decide/lic/Lic2Test.java, app/src/test/java/app/decide/lic/Lic3Test.java, app/src/test/java/app/decide/lic/Lic4Test.java
fixes #77 
This should also be compliant with new test formatting
=> Fix #77 erronous code
